package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Acteur generated by hbm2java
 */
public class Acteur  implements java.io.Serializable {


     private BigDecimal id;
     private PersonnelFilm personnelFilm;
     private Set filmActeurs = new HashSet(0);

    public Acteur() {
    }

	
    public Acteur(PersonnelFilm personnelFilm) {
        this.personnelFilm = personnelFilm;
    }
    public Acteur(PersonnelFilm personnelFilm, Set filmActeurs) {
       this.personnelFilm = personnelFilm;
       this.filmActeurs = filmActeurs;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public PersonnelFilm getPersonnelFilm() {
        return this.personnelFilm;
    }
    
    public void setPersonnelFilm(PersonnelFilm personnelFilm) {
        this.personnelFilm = personnelFilm;
    }
    public Set getFilmActeurs() {
        return this.filmActeurs;
    }
    
    public void setFilmActeurs(Set filmActeurs) {
        this.filmActeurs = filmActeurs;
    }




}


