package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CarteCredit generated by hbm2java
 */
public class CarteCredit  implements java.io.Serializable {


     private String numero;
     private Client client;
     private String typeCarte;
     private Date expiration;
     private BigDecimal cvv;

    public CarteCredit() {
    }

	
    public CarteCredit(String numero, String typeCarte, Date expiration, BigDecimal cvv) {
        this.numero = numero;
        this.typeCarte = typeCarte;
        this.expiration = expiration;
        this.cvv = cvv;
    }
    public CarteCredit(String numero, Client client, String typeCarte, Date expiration, BigDecimal cvv) {
       this.numero = numero;
       this.client = client;
       this.typeCarte = typeCarte;
       this.expiration = expiration;
       this.cvv = cvv;
    }
   
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getTypeCarte() {
        return this.typeCarte;
    }
    
    public void setTypeCarte(String typeCarte) {
        this.typeCarte = typeCarte;
    }
    public Date getExpiration() {
        return this.expiration;
    }
    
    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }
    public BigDecimal getCvv() {
        return this.cvv;
    }
    
    public void setCvv(BigDecimal cvv) {
        this.cvv = cvv;
    }




}


