package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private BigDecimal id;
     private Profile profile;
     private Set carteCredits = new HashSet(0);

    public Client() {
    }

	
    public Client(Profile profile) {
        this.profile = profile;
    }
    public Client(Profile profile, Set carteCredits) {
       this.profile = profile;
       this.carteCredits = carteCredits;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public Set getCarteCredits() {
        return this.carteCredits;
    }
    
    public void setCarteCredits(Set carteCredits) {
        this.carteCredits = carteCredits;
    }




}


