package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private BigDecimal id;
     private Profile profile;
     private String matricule;

    public Employe() {
    }

    public Employe(Profile profile, String matricule) {
       this.profile = profile;
       this.matricule = matricule;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }




}


