package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1



/**
 * FilmActeur generated by hbm2java
 */
public class FilmActeur  implements java.io.Serializable {


     private FilmActeurId id;
     private Tournage tournage;
     private Acteur acteur;
     private String nomPersonnage;

    public FilmActeur() {
    }

    public FilmActeur(FilmActeurId id, Tournage tournage, Acteur acteur, String nomPersonnage) {
       this.id = id;
       this.tournage = tournage;
       this.acteur = acteur;
       this.nomPersonnage = nomPersonnage;
    }
   
    public FilmActeurId getId() {
        return this.id;
    }
    
    public void setId(FilmActeurId id) {
        this.id = id;
    }
    public Tournage getTournage() {
        return this.tournage;
    }
    
    public void setTournage(Tournage tournage) {
        this.tournage = tournage;
    }
    public Acteur getActeur() {
        return this.acteur;
    }
    
    public void setActeur(Acteur acteur) {
        this.acteur = acteur;
    }
    public String getNomPersonnage() {
        return this.nomPersonnage;
    }
    
    public void setNomPersonnage(String nomPersonnage) {
        this.nomPersonnage = nomPersonnage;
    }




}


