package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FilmCopie generated by hbm2java
 */
public class FilmCopie  implements java.io.Serializable {


     private BigDecimal id;
     private Film film;
     private Set pretCourants = new HashSet(0);

    public FilmCopie() {
    }

	
    public FilmCopie(BigDecimal id, Film film) {
        this.id = id;
        this.film = film;
    }
    public FilmCopie(BigDecimal id, Film film, Set pretCourants) {
       this.id = id;
       this.film = film;
       this.pretCourants = pretCourants;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Set getPretCourants() {
        return this.pretCourants;
    }
    
    public void setPretCourants(Set pretCourants) {
        this.pretCourants = pretCourants;
    }




}


