package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Forfait generated by hbm2java
 */
public class Forfait  implements java.io.Serializable {


     private String nom;
     private BigDecimal cout;
     private BigDecimal locationMax;
     private BigDecimal dureeMax;
     private Set membres = new HashSet(0);

    public Forfait() {
    }

	
    public Forfait(String nom, BigDecimal cout, BigDecimal locationMax, BigDecimal dureeMax) {
        this.nom = nom;
        this.cout = cout;
        this.locationMax = locationMax;
        this.dureeMax = dureeMax;
    }
    public Forfait(String nom, BigDecimal cout, BigDecimal locationMax, BigDecimal dureeMax, Set membres) {
       this.nom = nom;
       this.cout = cout;
       this.locationMax = locationMax;
       this.dureeMax = dureeMax;
       this.membres = membres;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public BigDecimal getCout() {
        return this.cout;
    }
    
    public void setCout(BigDecimal cout) {
        this.cout = cout;
    }
    public BigDecimal getLocationMax() {
        return this.locationMax;
    }
    
    public void setLocationMax(BigDecimal locationMax) {
        this.locationMax = locationMax;
    }
    public BigDecimal getDureeMax() {
        return this.dureeMax;
    }
    
    public void setDureeMax(BigDecimal dureeMax) {
        this.dureeMax = dureeMax;
    }
    public Set getMembres() {
        return this.membres;
    }
    
    public void setMembres(Set membres) {
        this.membres = membres;
    }




}


