package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Membre generated by hbm2java
 */
public class Membre  implements java.io.Serializable {


     private BigDecimal id;
     private Adresse adresse;
     private Forfait forfait;
     private Profile profile;

    public Membre() {
    }

    public Membre(Adresse adresse, Forfait forfait, Profile profile) {
       this.adresse = adresse;
       this.forfait = forfait;
       this.profile = profile;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Adresse getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(Adresse adresse) {
        this.adresse = adresse;
    }
    public Forfait getForfait() {
        return this.forfait;
    }
    
    public void setForfait(Forfait forfait) {
        this.forfait = forfait;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }




}


