package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PaysProduction generated by hbm2java
 */
public class PaysProduction  implements java.io.Serializable {


     private String nom;
     private Set films = new HashSet(0);

    public PaysProduction() {
    }

	
    public PaysProduction(String nom) {
        this.nom = nom;
    }
    public PaysProduction(String nom, Set films) {
       this.nom = nom;
       this.films = films;
    }
   
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getFilms() {
        return this.films;
    }
    
    public void setFilms(Set films) {
        this.films = films;
    }




}


