package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PersonnelFilm generated by hbm2java
 */
public class PersonnelFilm  implements java.io.Serializable {


     private BigDecimal id;
     private String nom;
     private String prenom;
     private Date dateNaissance;
     private String lieuNaissance;
     private String biographie;
     private Scenariste scenariste;
     private Realisateur realisateur;
     private Acteur acteur;

    public PersonnelFilm() {
    }

	
    public PersonnelFilm(BigDecimal id, String nom, String prenom) {
        this.id = id;
        this.nom = nom;
        this.prenom = prenom;
    }
    public PersonnelFilm(BigDecimal id, String nom, String prenom, Date dateNaissance, String lieuNaissance, String biographie, Scenariste scenariste, Realisateur realisateur, Acteur acteur) {
       this.id = id;
       this.nom = nom;
       this.prenom = prenom;
       this.dateNaissance = dateNaissance;
       this.lieuNaissance = lieuNaissance;
       this.biographie = biographie;
       this.scenariste = scenariste;
       this.realisateur = realisateur;
       this.acteur = acteur;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public String getLieuNaissance() {
        return this.lieuNaissance;
    }
    
    public void setLieuNaissance(String lieuNaissance) {
        this.lieuNaissance = lieuNaissance;
    }
    public String getBiographie() {
        return this.biographie;
    }
    
    public void setBiographie(String biographie) {
        this.biographie = biographie;
    }
    public Scenariste getScenariste() {
        return this.scenariste;
    }
    
    public void setScenariste(Scenariste scenariste) {
        this.scenariste = scenariste;
    }
    public Realisateur getRealisateur() {
        return this.realisateur;
    }
    
    public void setRealisateur(Realisateur realisateur) {
        this.realisateur = realisateur;
    }
    public Acteur getActeur() {
        return this.acteur;
    }
    
    public void setActeur(Acteur acteur) {
        this.acteur = acteur;
    }




}


