package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PretCourant generated by hbm2java
 */
public class PretCourant  implements java.io.Serializable {


     private BigDecimal id;
     private Profile profile;
     private FilmCopie filmCopie;
     private Date datePret;
     private Date dateRetour;
     private String etatPret;

    public PretCourant() {
    }

    public PretCourant(BigDecimal id, Profile profile, FilmCopie filmCopie, Date datePret, Date dateRetour, String etatPret) {
       this.id = id;
       this.profile = profile;
       this.filmCopie = filmCopie;
       this.datePret = datePret;
       this.dateRetour = dateRetour;
       this.etatPret = etatPret;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public FilmCopie getFilmCopie() {
        return this.filmCopie;
    }
    
    public void setFilmCopie(FilmCopie filmCopie) {
        this.filmCopie = filmCopie;
    }
    public Date getDatePret() {
        return this.datePret;
    }
    
    public void setDatePret(Date datePret) {
        this.datePret = datePret;
    }
    public Date getDateRetour() {
        return this.dateRetour;
    }
    
    public void setDateRetour(Date dateRetour) {
        this.dateRetour = dateRetour;
    }
    public String getEtatPret() {
        return this.etatPret;
    }
    
    public void setEtatPret(String etatPret) {
        this.etatPret = etatPret;
    }




}


