package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private BigDecimal id;
     private String courriel;
     private String prenom;
     private String nom;
     private String tel;
     private Date dateNaissance;
     private String motDePasse;
     private Membre membre;
     private Employe employe;
     private Set pretCourants = new HashSet(0);
     private Client client;

    public Profile() {
    }

	
    public Profile(BigDecimal id, String courriel, String prenom, String nom, String tel, Date dateNaissance, String motDePasse) {
        this.id = id;
        this.courriel = courriel;
        this.prenom = prenom;
        this.nom = nom;
        this.tel = tel;
        this.dateNaissance = dateNaissance;
        this.motDePasse = motDePasse;
    }
    public Profile(BigDecimal id, String courriel, String prenom, String nom, String tel, Date dateNaissance, String motDePasse, Membre membre, Employe employe, Set pretCourants, Client client) {
       this.id = id;
       this.courriel = courriel;
       this.prenom = prenom;
       this.nom = nom;
       this.tel = tel;
       this.dateNaissance = dateNaissance;
       this.motDePasse = motDePasse;
       this.membre = membre;
       this.employe = employe;
       this.pretCourants = pretCourants;
       this.client = client;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }
    public Set getPretCourants() {
        return this.pretCourants;
    }
    
    public void setPretCourants(Set pretCourants) {
        this.pretCourants = pretCourants;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }




}


