package movierental;
// Generated 2018-11-22 14:13:58 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tournage generated by hbm2java
 */
public class Tournage  implements java.io.Serializable {


     private BigDecimal filmId;
     private Film film;
     private Realisateur realisateur;
     private Set filmActeurs = new HashSet(0);
     private Set scenaristes = new HashSet(0);

    public Tournage() {
    }

	
    public Tournage(Film film, Realisateur realisateur) {
        this.film = film;
        this.realisateur = realisateur;
    }
    public Tournage(Film film, Realisateur realisateur, Set filmActeurs, Set scenaristes) {
       this.film = film;
       this.realisateur = realisateur;
       this.filmActeurs = filmActeurs;
       this.scenaristes = scenaristes;
    }
   
    public BigDecimal getFilmId() {
        return this.filmId;
    }
    
    public void setFilmId(BigDecimal filmId) {
        this.filmId = filmId;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Realisateur getRealisateur() {
        return this.realisateur;
    }
    
    public void setRealisateur(Realisateur realisateur) {
        this.realisateur = realisateur;
    }
    public Set getFilmActeurs() {
        return this.filmActeurs;
    }
    
    public void setFilmActeurs(Set filmActeurs) {
        this.filmActeurs = filmActeurs;
    }
    public Set getScenaristes() {
        return this.scenaristes;
    }
    
    public void setScenaristes(Set scenaristes) {
        this.scenaristes = scenaristes;
    }




}


