CREATE OR REPLACE FUNCTION main.is_alphanum(string1 VARCHAR)
  RETURN VARCHAR IS

BEGIN
    IF (LENGTH(TRIM(TRANSLATE(string1, 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ+-.0123456789', ' '))) > 0) THEN
        RETURN 'FALSE';
    ELSE
        RETURN 'TRUE';
    END IF;
END;